# Generated by Django 3.0.12 on 2021-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210223_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='result',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
