# Generated by Django 3.0.12 on 2021-02-26 10:41

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210223_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
