# Generated by Django 3.0.12 on 2021-03-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210226_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
